# Generated by Django 3.1.2 on 2025-03-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buymodel',
            name='order_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('out for delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='pending', max_length=20, null=True),
        ),
    ]
